"use strict";
const assert = require("node:assert/strict"), fs = require("node:fs"), path = require("node:path");
const { fromFile } = require("./chat_dom.cjs");
const { createChatView } = require(path.join(process.argv[2], "chat-view.js"));
const doc = fromFile(path.join(process.argv[2], "index.html"));
const view = createChatView(doc);
const answer = JSON.parse(fs.readFileSync(process.argv[3], "utf8"));
const turn = {run_id:"transit-1", status:"completed", question:"回龙观到王府井的公共交通路线", answer};
view.updateTurn(turn, false);
const messages = doc.getElementById("chat-messages");
const details = messages.querySelector("details");
assert(details);
assert.equal(details.open, false);
const legs = messages.querySelectorAll("li").map(item=>item.textContent);
assert.equal(legs.length, 5);
assert(legs[1].includes("地铁13号线") && legs[1].includes("龙泽") && legs[1].includes("霍营"));
assert(legs[3].includes("换乘") && legs[3].includes("地铁8号线") && legs[3].includes("金鱼胡同"));
details.open = true;
view.updateTurn(turn, false);
assert.equal(messages.querySelector("details").open, true);
const saved = JSON.parse(JSON.stringify(turn));
view.renderSession({turns:new Map([[saved.run_id,saved]]),orderedRunIds:[saved.run_id],historyCursor:null});
assert.deepEqual(messages.querySelectorAll("li").map(item=>item.textContent), legs);
assert.equal(messages.querySelector("details").open, false);
assert.equal(messages.querySelectorAll("a").length, 1);
console.log("real transit legs survive rendering, expansion and history restoration");
